version: "3.8"

services:

  configserver:
    image: hounangogogo/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - hounan-network

  accounts:
    image: hounangogogo/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - hounan-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: hounangogogo/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - hounan-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: hounangogogo/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - hounan-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  hounan-network: