spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      rate: 1

  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Gateway server microservice
    description: hounan bank gateway server app
    version: 1.0.0
logging:
  level:
    come:
      hounan:
        gatewayserver: DEBUG
