# Spring Config
spring:
  devtools:
    restart:
      enabled: true

  application:
    name: accounts

  profiles:
    active: prod

  config:
    import: optional:configserver:http://localhost:8071

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

# server config
server:
  port: 8080

# management config
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    shutdown: true

#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# info endpoint
info:
  app:
    name: Account Mircoroservice
    description: Bank account app
    version: 1.0.0

# circuit breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      detailsForCustomerSupportApp:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2
