version: "3.8"

services:

  configserver:
    image: hounangogogo/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - hounan-network

  eurekaserver:
    image: hounangogogo/eurekaserver
    mem_limit: 800m
    ports:
      - "8070:8070"
    networks:
      - hounan-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: hounangogogo/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - hounan-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: hounangogogo/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - hounan-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: hounangogogo/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - hounan-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  hounan-network: