version: "3.8"

services:
  accounts:
    image: hounangogogo/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - hounan-network

  loans:
    image: hounangogogo/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - hounan-network

  cards:
    image: hounangogogo/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - hounan-network

networks:
  hounan-network: